# Service Account and RBAC for Prometheus Backup CronJob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-backup
  namespace: observability
  labels:
    app: prometheus-backup
    component: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-backup
  namespace: observability
  labels:
    app: prometheus-backup
    component: backup
rules:
  # Access to Prometheus pods for snapshot creation
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs: ["get", "list"]

  # Access to services
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-backup
  namespace: observability
  labels:
    app: prometheus-backup
    component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-backup
subjects:
  - kind: ServiceAccount
    name: prometheus-backup
    namespace: observability
