apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
      log_level: info

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
      ring:
        kvstore:
          store: memberlist

    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m
      max_block_bytes: 1048576
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        tokens_file_path: /var/tempo/wal/tokens

    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 168h
        compacted_block_retention: 24h
        retention_concurrency: 10
      ring:
        kvstore:
          store: memberlist

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: health-tracker
      storage:
        path: /var/tempo/data/generator/wal
        remote_write:
          - url: http://prometheus.observability.svc.cluster.local:9090/api/v1/write
            send_exemplars: true
      processor:
        service_graphs:
          dimensions:
            - service.name
            - service.namespace
            - workflow
          max_items: 10000
          workers: 10
        span_metrics:
          dimensions:
            - http.method
            - http.status_code
            - service.name

    querier:
      max_concurrent_queries: 20

    query_frontend:
      search:
        max_duration: 0s
      trace_by_id:
        query_shards: 50

    storage:
      trace:
        backend: s3
        wal:
          path: /var/tempo/wal
          encoding: snappy
        s3:
          bucket: tempo-traces-health-tracker
          endpoint: s3.us-east-1.amazonaws.com
          region: us-east-1
          insecure: false
          forcepathstyle: false
        block:
          version: vParquet3
          encoding: snappy
          row_group_size_bytes: 100000000
        pool:
          max_workers: 100
          queue_depth: 10000

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - tempo-headless.observability.svc.cluster.local:7946

    overrides:
      defaults:
        ingestion_rate_limit_bytes: 100000000
        ingestion_burst_size_bytes: 200000000
        max_traces_per_user: 100000
        max_search_bytes_per_trace: 100000
        max_bytes_per_trace: 50000000
        block_retention: 168h

    usage_report:
      reporting_enabled: false
