apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3-credentials
  namespace: observability
type: Opaque
stringData:
  access-key-id: "REPLACE_WITH_ACCESS_KEY_ID"
  secret-access-key: "REPLACE_WITH_SECRET_ACCESS_KEY"
