---
apiVersion: v1
kind: Service
metadata:
  name: tempo-headless
  namespace: observability
  labels:
    app: tempo
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 3200
    targetPort: http
  - name: otlp-grpc
    port: 4317
    targetPort: otlp-grpc
  - name: otlp-http
    port: 4318
    targetPort: otlp-http
  - name: grpc
    port: 9095
    targetPort: grpc
  - name: memberlist
    port: 7946
    targetPort: memberlist
  - name: jaeger-http
    port: 14268
    targetPort: jaeger-http
  selector:
    app: tempo

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observability
  labels:
    app: tempo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3200"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3200
    targetPort: http
  - name: otlp-grpc
    port: 4317
    targetPort: otlp-grpc
  - name: otlp-http
    port: 4318
    targetPort: otlp-http
  - name: jaeger-http
    port: 14268
    targetPort: jaeger-http
  selector:
    app: tempo
