# Alertmanager ServiceAccount
# Minimal permissions for alert management
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: observability
  labels:
    app: alertmanager
    component: alerting
