# Service Account and RBAC for Grafana Dashboard Backup CronJob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-dashboard-backup
  namespace: observability
  labels:
    app: grafana-dashboard-backup
    component: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-dashboard-backup
  namespace: observability
  labels:
    app: grafana-dashboard-backup
    component: backup
rules:
  # Access to Grafana service for API calls
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list"]

  # Access to pods for debugging
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-dashboard-backup
  namespace: observability
  labels:
    app: grafana-dashboard-backup
    component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-dashboard-backup
subjects:
  - kind: ServiceAccount
    name: grafana-dashboard-backup
    namespace: observability
