# Prometheus Service
# Provides stable network access to Prometheus pods
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
  labels:
    app: prometheus
    component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: grpc
      port: 10901
      targetPort: 10901
      protocol: TCP
    - name: thanos-http
      port: 10902
      targetPort: 10902
      protocol: TCP
  selector:
    app: prometheus
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours

---
# External Service for UI access
apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: observability
  labels:
    app: prometheus
    component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
