# Prometheus ServiceAccount and RBAC
# Provides permissions for Kubernetes service discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: observability
  labels:
    app: prometheus
    component: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: monitoring
rules:
  # Access to nodes and node metrics
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
    verbs: ["get", "list", "watch"]

  # Access to services and endpoints for service discovery
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]

  # Access to configmaps for configuration
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]

  # Access to ingress for service discovery
  - apiGroups: ["networking.k8s.io", "extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

  # Non-resource URLs for cluster metrics
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: observability
