# Thanos Object Storage Configuration Secret
# Contains S3 bucket configuration and credentials for long-term storage
#
# IMPORTANT: This is a template file for documentation purposes.
# DO NOT commit actual credentials to git!
#
# To create the secret in your cluster:
#
# 1. Create objstore.yml with your S3 configuration:
#    ---
#    type: S3
#    config:
#      bucket: "prometheus-long-term-storage"
#      endpoint: "s3.us-east-1.amazonaws.com"
#      region: "us-east-1"
#      # Optional: Use IRSA (IAM Roles for Service Accounts) for authentication
#      # Or provide access_key and secret_key via environment variables
#
# 2. Create the secret:
#    kubectl create secret generic thanos-objstore-config \
#      -n observability \
#      --from-file=objstore.yml=objstore.yml
#
# 3. (Optional) Create credentials secret if not using IRSA:
#    kubectl create secret generic thanos-objstore-secret \
#      -n observability \
#      --from-literal=access_key_id=YOUR_ACCESS_KEY \
#      --from-literal=secret_access_key=YOUR_SECRET_KEY
#
# For development/testing, you can create a minimal config:
#
# kubectl create secret generic thanos-objstore-config \
#   -n observability \
#   --from-literal=objstore.yml='
#   type: S3
#   config:
#     bucket: prometheus-test-bucket
#     endpoint: s3.us-east-1.amazonaws.com
#     region: us-east-1
#   '
#
# The Thanos sidecar will:
# - Upload 2h blocks to S3 after they are compacted
# - Downsample data to 5m and 1h resolutions
# - Enable unlimited retention in object storage
# - Reduce local storage requirements
#
# Cost estimate:
# - S3 Standard-IA: ~$0.0125/GB/month
# - 90 days * 1TB ≈ $11.25/month for archival
# - vs. Block storage: ~$0.10/GB/month = $100/month
# - Savings: ~$89/month per TB
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: observability
  labels:
    app: prometheus
    component: thanos
type: Opaque
stringData:
  objstore.yml: |
    # TEMPLATE - Replace with actual configuration
    # This configuration is for documentation only
    type: S3
    config:
      bucket: "REPLACE_WITH_YOUR_BUCKET_NAME"
      endpoint: "s3.REPLACE_WITH_YOUR_REGION.amazonaws.com"
      region: "REPLACE_WITH_YOUR_REGION"
      # For production, use IRSA (IAM Roles for Service Accounts)
      # or provide credentials via thanos-objstore-secret

---
# Optional: Credentials secret (use IRSA in production instead)
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: observability
  labels:
    app: prometheus
    component: thanos
type: Opaque
stringData:
  access_key_id: "REPLACE_WITH_YOUR_ACCESS_KEY"
  secret_access_key: "REPLACE_WITH_YOUR_SECRET_KEY"
