apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
  labels:
    app: loki
    component: log-aggregation
data:
  aws.region: "us-east-1"
  s3.bucket: "loki-logs-health-tracker"

  loki-config.yaml: |
    # Loki Configuration for Kubernetes
    # Single-binary mode with S3 backend

    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s

    # Common configuration for all components
    common:
      path_prefix: /loki/data
      storage:
        s3:
          endpoint: s3.us-east-1.amazonaws.com
          bucketnames: loki-logs-health-tracker
          region: us-east-1
          s3forcepathstyle: false
          insecure: false
          sse_encryption: true
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    # Memberlist configuration for clustering
    memberlist:
      join_members:
        - loki-headless.observability.svc.cluster.local:7946
      bind_port: 7946

    # Distributor configuration
    distributor:
      ring:
        kvstore:
          store: memberlist

    # Ingester configuration
    ingester:
      lifecycler:
        ring:
          replication_factor: 1
          kvstore:
            store: memberlist
        final_sleep: 0s

      # WAL configuration
      wal:
        enabled: true
        dir: /loki/wal
        flush_on_shutdown: true
        replay_memory_ceiling: 1GB

      # Chunk configuration
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      chunk_block_size: 262144
      chunk_target_size: 1536000
      chunk_encoding: snappy
      max_chunk_age: 2h
      max_transfer_retries: 0

    # Schema configuration
    schema_config:
      configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h

    # Storage configuration
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/data/index
        cache_location: /loki/data/cache
        cache_ttl: 24h
        shared_store: s3

      # Index cache
      index_queries_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 500
          ttl: 24h

    # Compactor configuration
    compactor:
      working_directory: /loki/data/compactor
      shared_store: s3
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

    # Query configuration
    querier:
      max_concurrent: 10
      query_timeout: 5m
      engine:
        timeout: 5m

    # Query scheduler
    query_scheduler:
      max_outstanding_requests_per_tenant: 2048

    # Query frontend
    frontend:
      max_outstanding_per_tenant: 2048
      compress_responses: true
      log_queries_longer_than: 10s

    # Query range configuration
    query_range:
      align_queries_with_step: true
      max_retries: 5
      parallelise_shardable_queries: true
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 500
            ttl: 24h

    # Limits configuration
    limits_config:
      # Retention period: 30 days
      retention_period: 720h

      # Ingestion limits
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_streams_per_user: 10000
      max_global_streams_per_user: 100000

      # Query limits
      max_query_length: 721h
      max_query_parallelism: 32
      max_query_series: 10000
      max_entries_limit_per_query: 10000
      max_cache_freshness_per_query: 10m

      # Label limits
      max_label_name_length: 1024
      max_label_value_length: 2048
      max_label_names_per_series: 30

      # Reject old samples
      reject_old_samples: true
      reject_old_samples_max_age: 168h

      # Per-stream rate limiting
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 15MB

      # Split queries by interval
      split_queries_by_interval: 15m

    # Chunk store cache
    chunk_store_config:
      max_look_back_period: 720h
      cache_lookups_older_than: 0s
      chunk_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 1000
          ttl: 24h

    # Table manager
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h

    # Ruler configuration (for alerts)
    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /tmp/loki/rules-temp
      alertmanager_url: http://alertmanager.observability.svc.cluster.local:9093
      ring:
        kvstore:
          store: memberlist
      enable_api: true
      enable_alertmanager_v2: true

    # Analytics (disabled)
    analytics:
      reporting_enabled: false

    # Tracing
    tracing:
      enabled: false
