apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    monitoring: enabled
    istio-injection: disabled
  annotations:
    description: "Observability stack namespace for Loki, Prometheus, Tempo, and Grafana"
