# S3 Credentials Secret
# NOTE: In production, use External Secrets Operator or IAM roles for Kubernetes
# This file should be encrypted or managed via sealed-secrets

apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
  namespace: observability
  labels:
    app: loki
    component: log-aggregation
type: Opaque
stringData:
  # Replace with actual credentials or use IAM roles
  access-key-id: "REPLACE_WITH_ACCESS_KEY_ID"
  secret-access-key: "REPLACE_WITH_SECRET_ACCESS_KEY"

---
# Example of using External Secrets Operator (commented out)
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: loki-s3-credentials
#   namespace: observability
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: aws-secrets-manager
#     kind: SecretStore
#   target:
#     name: loki-s3-credentials
#     creationPolicy: Owner
#   data:
#   - secretKey: access-key-id
#     remoteRef:
#       key: loki/s3-credentials
#       property: access_key_id
#   - secretKey: secret-access-key
#     remoteRef:
#       key: loki/s3-credentials
#       property: secret_access_key
