---
# Headless service for StatefulSet DNS
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: observability
  labels:
    app: loki
    component: log-aggregation
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 3100
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
  - name: memberlist
    port: 7946
    targetPort: memberlist
    protocol: TCP
  selector:
    app: loki

---
# Regular service for accessing Loki
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
  labels:
    app: loki
    component: log-aggregation
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3100
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
  selector:
    app: loki
  sessionAffinity: None
