apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: observability
  labels:
    app: loki
    component: log-aggregation
  annotations:
    # EKS IAM role annotation (update with actual role ARN in production)
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/loki-s3-access

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki
  labels:
    app: loki
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki
  labels:
    app: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki
subjects:
- kind: ServiceAccount
  name: loki
  namespace: observability
