---
# ClusterIssuer for Let's Encrypt (production)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@health-tracker.example.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
# Self-signed issuer for development
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Certificate for OTel Collector
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-tls
  namespace: observability
spec:
  secretName: otel-collector-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  subject:
    organizations:
      - health-tracker
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - otel-collector.observability.svc.cluster.local
    - otel-collector.observability.svc
    - otel-collector.observability
    - otel-collector
  issuerRef:
    name: selfsigned-issuer  # Use selfsigned-issuer for dev, letsencrypt-prod for production
    kind: ClusterIssuer
    group: cert-manager.io
