apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
    component: telemetry
    version: v0.96.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
        component: telemetry
        version: v0.96.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/metrics"
    spec:
      # Anti-affinity to spread replicas across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - otel-collector
                topologyKey: kubernetes.io/hostname

      # Service account for Kubernetes API access
      serviceAccountName: otel-collector

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534  # nobody user
        fsGroup: 65534

      containers:
        - name: otel-collector
          image: health-tracker/otel-collector:0.96.0
          imagePullPolicy: IfNotPresent

          # Command and args
          args:
            - --config=/etc/otelcol/config.yaml

          # Ports
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: prometheus
              containerPort: 8889
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: health
              containerPort: 13133
              protocol: TCP
            - name: zpages
              containerPort: 55679
              protocol: TCP

          # Environment variables
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          # Resource requests and limits
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi

          # Volume mounts
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
              readOnly: true
            - name: tls-certs
              mountPath: /etc/otel/tls
              readOnly: true
            - name: auth-token
              mountPath: /etc/otel/auth
              readOnly: true

          # Liveness probe
          livenessProbe:
            httpGet:
              path: /health/status
              port: health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            httpGet:
              path: /health/status
              port: health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

      # Volumes
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: tls-certs
          secret:
            secretName: otel-collector-tls
            optional: true  # Allow deployment without TLS for initial setup
        - name: auth-token
          secret:
            secretName: otel-collector-auth
            optional: true  # Allow deployment without auth for initial setup

      # Termination grace period
      terminationGracePeriodSeconds: 30
