apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
    component: telemetry
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
    - name: prometheus
      port: 8889
      targetPort: prometheus
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
    - name: health
      port: 13133
      targetPort: health
      protocol: TCP
    - name: zpages
      port: 55679
      targetPort: zpages
      protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-headless
  namespace: observability
  labels:
    app: otel-collector
    component: telemetry
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
