apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/name: alertmanager
  app.kubernetes.io/instance: alertmanager
  app.kubernetes.io/version: "0.26.0"
  app.kubernetes.io/component: alerting
  app.kubernetes.io/part-of: observability-stack

replicas:
  - name: alertmanager
    count: 2
