apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: observability
  labels:
    app: alertmanager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-headless
  namespace: observability
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
    - name: gossip-tcp
      port: 9094
      targetPort: 9094
      protocol: TCP
    - name: gossip-udp
      port: 9094
      targetPort: 9094
      protocol: UDP
  selector:
    app: alertmanager
