apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: observability
  labels:
    app: alertmanager
spec:
  serviceName: alertmanager-headless
  replicas: 2  # HA deployment with 2 replicas
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      serviceAccountName: alertmanager
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534  # nobody user
        fsGroup: 65534

      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.26.0
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager/data'
            - '--data.retention=120h'  # 5 days retention for silences/notifications
            - '--web.listen-address=:9093'
            # Gossip clustering for HA
            - '--cluster.listen-address=0.0.0.0:9094'
            - '--cluster.advertise-address=$(POD_IP):9094'
            - '--cluster.peer=alertmanager-0.alertmanager-headless.observability.svc.cluster.local:9094'
            - '--cluster.peer=alertmanager-1.alertmanager-headless.observability.svc.cluster.local:9094'
            - '--cluster.reconnect-timeout=5m'
            - '--log.level=info'

          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
            - name: gossip-tcp
              containerPort: 9094
              protocol: TCP
            - name: gossip-udp
              containerPort: 9094
              protocol: UDP

          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: templates
              mountPath: /etc/alertmanager/templates
            - name: data
              mountPath: /alertmanager/data

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

        # Config reloader sidecar - reloads config on changes
        - name: config-reloader
          image: jimmidyson/configmap-reload:v0.8.0
          args:
            - '--volume-dir=/etc/alertmanager'
            - '--webhook-url=http://localhost:9093/-/reload'
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi

      volumes:
        - name: config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
        - name: templates
          configMap:
            name: alertmanager-config
            items:
              - key: email.default.tmpl
                path: email.default.tmpl
              - key: email.high.tmpl
                path: email.high.tmpl

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: alertmanager
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard  # Adjust based on your cluster
