spring:
  application:
    name: health-tracker-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/healthtracker
    username: admin
    password: ${DB_PASSWORD:secret}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: 604800000  # 7 days in milliseconds
  refresh-token-expiration: 2592000000 # 30 days in milliseconds

# Encryption Configuration (for PHI data)
encryption:
  secret: ${ENCRYPTION_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    db:
      enabled: true

  # Distributed Tracing Configuration
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_RATE:0.1}  # 10% sampling rate (use 1.0 for dev)

  otlp:
    tracing:
      endpoint: ${JAEGER_ENDPOINT:http://jaeger:4318/v1/traces}

logging:
  level:
    root: INFO
    com.healthtracker.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false
