# Production Configuration
# ALL SECRETS MUST BE PROVIDED VIA ENVIRONMENT VARIABLES
# NO DEFAULTS ALLOWED IN PRODUCTION

# Production JWT Configuration - NO DEFAULTS
jwt:
  secret: ${JWT_SECRET}  # REQUIRED - must be set via environment
  access-token-expiration: 1800000  # 30 minutes (strict for production)
  refresh-token-expiration: 2592000000  # 30 days
  issuer: ${JWT_ISSUER}  # REQUIRED - e.g., "health-tracker-api"
  audience: ${JWT_AUDIENCE}  # REQUIRED - e.g., "health-tracker-app"

# Production Encryption Configuration - NO DEFAULTS
encryption:
  secret: ${ENCRYPTION_SECRET}  # REQUIRED - must be different from JWT secret
  salt: ${ENCRYPTION_SALT}  # REQUIRED - unique per deployment
  algorithm: AES/GCM/NoPadding

# Production CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}  # REQUIRED - e.g., "https://app.example.com"

# Rate Limiting - More restrictive for production
rate-limit:
  auth:
    # More restrictive: 3 attempts per 5 minutes
    capacity: 3
    refill-period-seconds: 300
    refill-tokens: 3
  cache:
    # Larger cache for production load
    maximum-size: 500000
    expire-after-access-seconds: 7200

server:
  cookie:
    secure: true  # Always use secure cookies in production (HTTPS)
  error:
    include-message: never  # Don't expose error details in production
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: WARN
    com.healthtracker.backend: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

management:
  # Distributed Tracing - 10% sampling for production performance
  tracing:
    sampling:
      probability: 0.1  # 10% sampling in production (adjust based on load)
