name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-and-test:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    # This workflow handles an npm workspaces monorepo:
    # - package-lock.json lives at repository root
    # - npm ci runs at root to install all workspace dependencies
    # - npm scripts run from ./frontend directory (where frontend/package.json is)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json  # Lock file at repository root

      - name: Install dependencies
        run: npm ci
        working-directory: .  # Install all workspace dependencies from root

      - name: Validate Design Tokens
        run: npm run tokens:check
        working-directory: ./frontend

      - name: Lint TypeScript
        run: npm run lint
        working-directory: ./frontend

      - name: Lint CSS
        run: npm run lint:css
        working-directory: ./frontend

      - name: Type Check
        run: npm run type-check
        working-directory: ./frontend

      - name: Run tests with coverage
        run: npm run test:coverage
        working-directory: ./frontend

      - name: Upload coverage reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: frontend/coverage/
          retention-days: 7

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/
          retention-days: 7
