name: Lint and Format Check

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/lint-and-format.yml'

jobs:
  eslint-check:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with annotations
        run: |
          cd frontend
          npm run lint -- --format=json --output-file=eslint-report.json || true
          npm run lint
        continue-on-error: false

      - name: Annotate ESLint results
        if: failure()
        run: |
          cd frontend
          if [ -f eslint-report.json ]; then
            node -e "
              const fs = require('fs');
              const results = JSON.parse(fs.readFileSync('eslint-report.json', 'utf8'));
              results.forEach(result => {
                if (result.messages.length > 0) {
                  result.messages.forEach(msg => {
                    const level = msg.severity === 2 ? 'error' : 'warning';
                    const file = result.filePath.replace(process.cwd() + '/', '');
                    console.log(\`::\${level} file=\${file},line=\${msg.line},col=\${msg.column}::\${msg.message} (\${msg.ruleId})\`);
                  });
                }
              });
            "
          fi

  prettier-check:
    name: Prettier Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check
        working-directory: ./frontend

  stylelint-check:
    name: Stylelint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        run: npm run lint:css
        working-directory: ./frontend
