name: Security Validation

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/security-validation.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/security-validation.yml'

  # Allow this workflow to be called by other workflows (e.g., validation-orchestrator)
  workflow_call:
    outputs:
      dependency-scan-status:
        description: 'Status of dependency vulnerability scanning'
        value: ${{ jobs.dependency-scan.outputs.scan-status }}
      sast-status:
        description: 'Status of static application security testing'
        value: ${{ jobs.sast.outputs.sast-status }}

# Cancel in-progress runs for the same workflow and branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Dependency scanning
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest

    outputs:
      scan-status: ${{ steps.set-outputs.outputs.scan-status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Maven wrapper
        working-directory: backend
        run: chmod +x mvnw

      - name: Run OWASP Dependency Check
        id: owasp-check
        working-directory: backend
        continue-on-error: true
        run: ./mvnw dependency-check:check -B

      - name: Run Snyk to check for vulnerabilities
        id: snyk-check
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=backend/pom.xml

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report-${{ github.sha }}
          path: backend/target/dependency-check-report.html
          retention-days: 7

      - name: Set scan output
        id: set-outputs
        if: always()
        run: |
          # Dependency scan is successful if OWASP check passes
          # Snyk failures are treated as warnings since they require a token
          if [ "${{ steps.owasp-check.outcome }}" = "success" ]; then
            echo "scan-status=success" >> $GITHUB_OUTPUT
          else
            echo "scan-status=failure" >> $GITHUB_OUTPUT
            echo "::error::OWASP Dependency Check found vulnerabilities"
            exit 1
          fi

          # Warning for Snyk failures (non-critical if token is missing)
          if [ "${{ steps.snyk-check.outcome }}" != "success" ]; then
            echo "::warning::Snyk vulnerability scan did not complete successfully"
          fi

  # Job 2: Static Application Security Testing (SAST)
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest

    outputs:
      sast-status: ${{ steps.set-outputs.outputs.sast-status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Maven wrapper
        working-directory: backend
        run: chmod +x mvnw

      - name: Run SonarQube analysis
        id: sonar-scan
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          if [ -n "$SONAR_TOKEN" ]; then
            ./mvnw sonar:sonar \
              -Dsonar.projectKey=health-tracker-backend \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.token=$SONAR_TOKEN \
              -B
          else
            echo "SonarQube token not configured, skipping analysis"
            exit 0
          fi
        continue-on-error: true

      - name: Set SAST output
        id: set-outputs
        if: always()
        run: |
          # SAST is treated as a warning if SonarQube is not configured
          # This allows the pipeline to continue even without SonarQube setup
          if [ "${{ steps.sonar-scan.outcome }}" = "success" ]; then
            echo "sast-status=success" >> $GITHUB_OUTPUT
          elif [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "sast-status=success" >> $GITHUB_OUTPUT
            echo "::warning::SonarQube not configured, skipping SAST"
          else
            echo "sast-status=failure" >> $GITHUB_OUTPUT
            echo "::warning::SAST scan did not complete successfully"
          fi
